export const AUDIO_THRESHOLDS = {
  MIC_TOO_QUIET: -40,
  MIC_TOO_LOUD: -6,
  NOISE_FLOOR_GOOD: -45,
  NOISE_FLOOR_NOISY: -35,
  NOISE_FLOOR_REJECT: -30,

  CLIP_WARNING_COUNT: 5,
  SILENCE_WARNING_MS: 30_000,
  SILENCE_THRESHOLD: -50,
  OVERLAP_WARNING_PCT: 20,
  TOO_QUIET_DURATION_MS: 10_000,

  P0_SNR_MIN: 25,
  P1_SNR_MIN: 20,
  P2_SNR_MIN: 15,
  P3_SNR_MIN: 10,

  TARGET_RMS_MIN: -26,
  TARGET_RMS_MAX: -20,
  TARGET_LUFS: -23,
} as const;

export type QualityProfile = 'P0' | 'P1' | 'P2' | 'P3' | 'P4';
